const Constants = {
    //ConditionType
    CONST_CONDITION_TYPE_INPUT: "INPUT",
    CONST_CONDITION_TYPE_SELECT: "SELECT",
    CONST_CONDITION_TYPE_BUTTON: "BUTTON",
    CONST_CONDITION_TYPE_DATE: "DATE",
    CONST_CONDITION_TYPE_RANGE: "RANGE",
    CONST_CONDITION_TYPE_UPLOAD: "UPLOAD",

    //EditableCellType
    CONST_EDITABLE_CELL_TYPE_INPUT: "Input",
    CONST_EDITABLE_CELL_TYPE_NUMBER: "Number",
    CONST_EDITABLE_CELL_TYPE_SELECT: "Select",
    CONST_EDITABLE_CELL_TYPE_DATE_PICKER: "DatePicker",

    //行内编辑的操作
    CONST_OPERATION_SAVE: "SAVE",
    CONST_OPERATION_CANCEL: "CANCEL",

    //是否显示
    CONST_TMS_STATE_YES: "YES",
    CONST_TMS_STATE_NO: "NO",

    //Column
    CONST_RENDER_NULL_VALUE: "--",
    CONST_ANTD_EMPTY_DATA: "empty-placeholder-data",

}

exports.Constants = Constants;